### ISSUE TITLE
Missing schema documentation for 'color' and 'iconUrl'

### ISSUE THREAD

**Issue by XDelta** [neos-modding-group/neos-modding-group.github.io#12]
These 2 props were added in this commit and not yet documented
https://github.com/neos-modding-group/neos-mod-manifest/commit/73fd82a52d727a81d116533bc85ac78fd3c2d1ea

**Comment by ljoonal** [comment]
- `iconUrl` should be a documented to be a publicly accessible URL that resolves to an image file (preferably in a common format like JPG/PNG, and its suitable for use as an icon, aka small filesize instead of an absurdly large image).
- `color` Should be documented to be the hex color without a leading `#` character

Both of these should not be marked as mandatory, and their usecase of customizing how the mods information might be displayed should be noted.

**Comment by Psychpsyo** [comment]
Documenting these now.
